# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TerraformTopoCorrection
                                 A QGIS plugin
 Topographically corrects provided input layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-02-27
        copyright            : (C) 2023 by Tigran Manasyan
        email                : t.manasyan@g.nsu.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Tigran Manasyan'
__date__ = '2023-02-27'
__copyright__ = '(C) 2023 by Tigran Manasyan'

from .CTopoCorrectionAlgorithm import CTopoCorrectionAlgorithm
from .CosineCTopoCorrectionAlgorithm import CosineCTopoCorrectionAlgorithm
from .CosineTTopoCorrectionAlgorithm import CosineTTopoCorrectionAlgorithm
from .MinnaertScsTopoCorrectionAlgorithm import MinnaertScsTopoCorrectionAlgorithm
from .MinnaertTopoCorrectionAlgorithm import MinnaertTopoCorrectionAlgorithm
from .PbcTopoCorrectionAlgorithm import PbcTopoCorrectionAlgorithm
from .PbmTopoCorrectionAlgorithm import PbmTopoCorrectionAlgorithm
from .ScsCTopoCorrectionAlgorithm import ScsCTopoCorrectionAlgorithm
from .ScsTopoCorrectionAlgorithm import ScsTopoCorrectionAlgorithm
from .TeilletRegressionTopoCorrectionAlgorithm import TeilletRegressionTopoCorrectionAlgorithm
from .VecaTopoCorrectionAlgorithm import VecaTopoCorrectionAlgorithm

DEFAULT_CORRECTIONS = [
    CosineTTopoCorrectionAlgorithm,
    CosineCTopoCorrectionAlgorithm,
    CTopoCorrectionAlgorithm,
    ScsTopoCorrectionAlgorithm,
    ScsCTopoCorrectionAlgorithm,
    MinnaertTopoCorrectionAlgorithm,
    MinnaertScsTopoCorrectionAlgorithm,
    PbmTopoCorrectionAlgorithm,
    VecaTopoCorrectionAlgorithm,
    TeilletRegressionTopoCorrectionAlgorithm,
    PbcTopoCorrectionAlgorithm
]
